# Generated by Django 4.1.5 on 2023-01-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isBuyer',
            field=models.BooleanField(default=True),
        ),
    ]
