# Generated by Django 4.1.5 on 2023-01-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_discountpercentage_product_isnew_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='farmerId',
            field=models.CharField(blank=True, default=5, max_length=5, null=True),
        ),
    ]
